pipeline {

    agent any

    tools {
        maven 'maven3'
    }

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/MaheshThaku/springboot-docker-demo.git'
            }
        }

        stage('Build Project') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t springboot-app .'
            }
        }

    }
}