spring.application.name=DockerProject

# Server port (optional)
server.port=8080

# MySQL Docker connection
spring.datasource.url=jdbc:mysql://mysql-container:3306/mydb
spring.datasource.username=root
spring.datasource.password=root987
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (optional but good)
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
